version: '3.8'
services:
  postgres:
    image: postgres
    container_name: track-life-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  localstack:
    image: localstack/localstack
    container_name: track-life-localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=${DEBUG:-1}
    volumes:
      - "./localstack/volume:/var/lib/localstack"
      - "./localstack/scripts:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  default:
    name: track-life-network
